import{ArrowRight,BadgeCheck,Clock3,Medal,Palette,ShieldCheck,Shirt,Timer,Users}from"lucide-react";import{getEvents}from"../lib/events";import{supabaseSelect}from"../lib/supabase";import{PortfolioGallery,QuoteForm,type PortfolioItem}from"./home-interactions";
export const dynamic="force-dynamic";
const date=(v:string)=>new Intl.DateTimeFormat("es-MX",{day:"2-digit",month:"short",year:"numeric",timeZone:"America/Mexico_City"}).format(new Date(v));
export default async function Home(){const events=await getEvents();let portfolio:PortfolioItem[]=[];try{portfolio=await supabaseSelect<PortfolioItem>("portfolio_items","select=id,category,title,description,image_url&order=sort_order.asc,created_at.desc")}catch{}return <main><header className="nav-shell"><a href="/" className="brand logo-brand"><img src="/nesport-logo.png" alt="Nesport"/></a><nav><a href="/">Inicio</a><a href="/carreras">Carreras</a><a href="#ofrecemos">Lo que ofrecemos</a><a href="#portafolio">Galería</a><a href="#cotizacion">Cotización</a><a href="/cronometro">Cronómetro</a></nav><a className="admin-link" href="/dashboard">Portal administrador</a></header>
<section className="hero home-hero"><div className="energy-orb orb-one"/><div className="energy-orb orb-two"/><div className="hero-copy"><span className="eyebrow"><span/> ORGANIZACIÓN DEPORTIVA INTEGRAL</span><h1>Tu próxima meta<br/><em>empieza aquí.</em></h1><p>Diseñamos, producimos y organizamos carreras atléticas que la gente recuerda: desde el concepto y la convocatoria hasta el kit, los dorsales y la meta.</p><div className="hero-actions"><a className="btn primary" href="/carreras">Ver carreras <ArrowRight size={18}/></a><a className="btn ghost" href="#ofrecemos">Conocer Nesport</a></div></div><div className="race-card brand-card"><div className="hero-logo-3d"><img src="/nesport-logo.png" alt="Logo Nesport"/></div><div className="track-lines"/><div className="race-card-bottom"><span>ORGANIZA</span><b>CORRE</b></div></div></section>
<div className="sport-ticker"><div><span>CARRERAS</span><b>•</b><span>KITS</span><b>•</b><span>DORSALES</span><b>•</b><span>MEDALLAS</span><b>•</b><span>CRONOMETRAJE</span><b>•</b><span>EXPERIENCIAS</span><b>•</b></div></div>
<section className="brand-statement"><span>DE LA IDEA A LA META</span><h2>Todo lo que una carrera necesita,<br/>en un solo equipo.</h2><p>Nesport coordina cada pieza del evento para que organizadores, patrocinadores y corredores vivan una experiencia clara, segura y emocionante.</p></section>
<section id="ofrecemos" className="content-section services-section"><div className="section-heading"><span>01 / LO QUE OFRECEMOS</span><h2>Corremos contigo en cada etapa</h2><p>Soluciones integrales para eventos atléticos, empresariales, deportivos y con causa.</p></div><div className="feature-grid"><article><Medal/><b>Producción integral</b><p>Planeación, logística, ruta, montaje, meta y coordinación operativa.</p></article><article><Shirt/><b>Kit oficial</b><p>Diseño y venta de playeras, dorsales, medallas y artículos para corredor.</p></article><article><BadgeCheck/><b>Registro seguro</b><p>Inscripciones, comprobantes, folios únicos y control de participantes.</p></article><article><Timer/><b>Control de tiempos</b><p>Cronómetro para corredores y consulta de tiempos desde administración.</p></article></div><div className="feature-grid second-row"><article><Palette/><b>Identidad del evento</b><p>Concepto gráfico, folletos, promocionales y materiales para redes.</p></article><article><Users/><b>Patrocinios</b><p>Espacios de marca, directorio de patrocinadores y activaciones.</p></article><article><ShieldCheck/><b>Datos protegidos</b><p>Responsiva, privacidad y contacto de emergencia en cada inscripción.</p></article><article><Clock3/><b>Seguimiento</b><p>Conteo regresivo, avisos y estado de cada carrera en tiempo real.</p></article></div></section>
<section id="portafolio" className="portfolio-section"><div className="portfolio-head"><span>02 / PORTAFOLIO REAL</span><h2>Diseño que también cruza la meta</h2><p>Explora playeras, medallas, dorsales y experiencias creadas por Nesport. Toca una imagen para verla completa.</p></div><PortfolioGallery items={portfolio}/></section>
<section className="official-sponsor"><div><span>PATROCINADOR OFICIAL</span><h2>La fuerza detrás<br/>de cada meta.</h2><p>CrossFit Ek’ Balam acompaña a Nesport impulsando una comunidad más fuerte, disciplinada y apasionada por el deporte.</p></div><div className="sponsor-emblem"><img src="/crossfit-ek-balam.png" alt="CrossFit Ek’ Balam, patrocinador oficial"/><span>OFFICIAL PARTNER</span></div></section>
<section className="races-preview"><div className="portfolio-head"><span>03 / CALENDARIO</span><h2>Próximas carreras</h2><p>Eventos vigentes para inscripción y nuevas experiencias en preparación.</p></div><div className="race-list">{events.map(e=><article key={e.id} className="event-card"><div className={`event-visual ${e.hero_image?"has-image":""}`} style={e.hero_image?{backgroundImage:`linear-gradient(0deg,#080808bb,#08080812),url(${e.hero_image})`}:undefined}>{!e.hero_image&&<span>{e.categories.split(",")[0]}</span>}<small>{e.status==="published"?"INSCRIPCIONES ABIERTAS":"PRÓXIMAMENTE"}</small></div><div className="event-info"><span>{date(e.event_date)} · {e.location}</span><h3>{e.title}</h3><p>{e.description}</p><div><b>{e.categories}</b><strong>$ {e.price} MXN</strong></div><a href={"/carreras/"+e.slug}>Ver carrera <ArrowRight/></a></div></article>)}</div><a className="btn dark" href="/carreras">Ver todas las carreras</a></section>
<section id="cotizacion" className="quote-section"><div className="quote-intro"><span>04 / ORGANIZA CON NESPORT</span><h2>Tu carrera comienza con una buena idea.</h2><p>Cuéntanos qué quieres organizar. Podemos encargarnos de la identidad, inscripciones, kits, producción, logística y cronometraje.</p><div><b>Respuesta personalizada</b><span>Recibiremos los datos del proyecto directamente en el administrador.</span></div></div><QuoteForm/></section>
<footer><div className="brand logo-brand footer-logo"><img src="/nesport-logo.png" alt="Nesport"/></div><p>Organizamos la carrera. Tú escribes la meta.</p><div><a href="/carreras">Carreras</a><a href="/cronometro">Cronómetro</a><a href="/dashboard">Administrador</a></div></footer></main>}
