"use client";
import{useRef,useState}from"react";import{CheckCircle2,Copy,FileText,ShieldCheck,Upload,X}from"lucide-react";
type Event={id:string;title:string;price:number;categories:string;bank_name:string;bank_holder:string;bank_account:string;bank_clabe:string;waiver:string;privacy:string};
export default function RegistrationForm({event}:{event:Event}){
 const formRef=useRef<HTMLFormElement>(null),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[folio,setFolio]=useState(""),[error,setError]=useState(""),[legal,setLegal]=useState<"waiver"|"privacy"|null>(null);
 function next(){const form=formRef.current;if(!form)return;const fields=[...form.querySelectorAll<HTMLElement>('[data-step="1"] input,[data-step="1"] select')];for(const field of fields){if(field instanceof HTMLInputElement||field instanceof HTMLSelectElement){if(!field.checkValidity()){field.reportValidity();return}}}setError("");setStep(2);form.scrollIntoView({behavior:"smooth",block:"start"})}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);fd.set("eventId",event.id);try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);const r=await fetch("/api/registrations",{method:"POST",body:fd,signal:controller.signal});clearTimeout(timer);const j=await r.json().catch(()=>({error:`El servidor respondió ${r.status}.` }));if(!r.ok)throw new Error(j.error||"No se pudo completar el registro");setFolio(j.folio);setStep(3)}catch(err){setError(err instanceof DOMException&&err.name==="AbortError"?"El registro tardó demasiado. Intenta nuevamente.":err instanceof Error?err.message:"Ocurrió un error")}finally{setBusy(false)}}
 if(step===3)return <div className="success-card"><CheckCircle2/><span>REGISTRO RECIBIDO</span><h3>¡Ya estás en la salida!</h3><p>Tu comprobante será validado por Nesport. Conserva este folio provisional:</p><strong>{folio}</strong><a className="btn primary" href="/cronometro">Ir al cronómetro</a></div>;
 return <><form ref={formRef} className="registration-form" onSubmit={submit}><div className="steps"><span className={step===1?"active":"done"}>1 <b>Datos</b></span><i/><span className={step===2?"active":""}>2 <b>Pago</b></span><i/><span>3 <b>Listo</b></span></div>
 <section data-step="1" hidden={step!==1}><div className="form-title"><small>DATOS DEL PARTICIPANTE</small><h3>Cuéntanos quién corre</h3></div><div className="form-grid"><label className="wide">Nombre completo<input required name="fullName" placeholder="Nombre(s) y apellidos"/></label><label>Correo electrónico<input required type="email" name="email" placeholder="correo@ejemplo.com"/></label><label>WhatsApp<input required name="phone" inputMode="tel" minLength={10} placeholder="10 dígitos"/></label><label>Fecha de nacimiento<input required type="date" name="birthDate"/></label><label>Rama<select required name="gender"><option value="">Selecciona</option><option>Varonil</option><option>Femenil</option></select></label><label>Categoría<select required name="category"><option value="">Selecciona</option>{event.categories.split(",").map(x=><option key={x.trim()}>{x.trim()}</option>)}</select></label><label>Talla de playera<select required name="shirtSize"><option value="">Selecciona</option>{["XS","S","M","L","XL","XXL"].map(x=><option key={x}>{x}</option>)}</select></label><label>Ciudad<input required name="city" placeholder="Ciudad y estado"/></label><label>Club, gym o empresa <small>(opcional)</small><input name="club" placeholder="Nombre del equipo"/></label><label>Contacto de emergencia<input required name="emergencyName" placeholder="Nombre completo"/></label><label>Teléfono de emergencia<input required name="emergencyPhone" inputMode="tel" minLength={10}/></label></div><div className="legal-box"><div className="legal-links"><button type="button" onClick={()=>setLegal("waiver")}><FileText/>Leer carta responsiva</button><button type="button" onClick={()=>setLegal("privacy")}><ShieldCheck/>Leer aviso de privacidad</button></div><label><input required type="checkbox" name="waiverAccepted" value="yes"/> Confirmo que leí y acepto la carta responsiva y el aviso de privacidad.</label></div><button type="button" className="btn primary full" onClick={next}>Continuar al pago <span>→</span></button></section>
 <section data-step="2" hidden={step!==2}><div className="form-title"><small>DATOS DE PAGO</small><h3>Último paso</h3></div><div className="bank-card"><div><small>BANCO</small><b>{event.bank_name}</b></div><div><small>TITULAR</small><b>{event.bank_holder}</b></div><div><small>CUENTA</small><b>{event.bank_account}</b><button type="button" onClick={()=>navigator.clipboard.writeText(event.bank_account)}><Copy size={15}/></button></div><div><small>CLABE</small><b>{event.bank_clabe}</b><button type="button" onClick={()=>navigator.clipboard.writeText(event.bank_clabe)}><Copy size={15}/></button></div><div className="bank-total"><small>TOTAL</small><strong>${event.price} MXN</strong></div></div><label className="upload-box"><Upload/><b>Sube tu comprobante</b><span>JPG, PNG o PDF · máximo 5 MB</span><input required name="receipt" type="file" accept="image/jpeg,image/png,application/pdf"/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="btn ghost" onClick={()=>setStep(1)}>Volver</button><button disabled={busy} className="btn primary" type="submit">{busy?"Enviando...":"Confirmar registro"}</button></div></section></form>
 {legal&&<div className="legal-modal-backdrop" onMouseDown={()=>setLegal(null)}><article className="legal-modal" onMouseDown={e=>e.stopPropagation()}><button className="legal-close" onClick={()=>setLegal(null)} aria-label="Cerrar"><X/></button><span>{legal==="waiver"?"DOCUMENTO DEL PARTICIPANTE":"PROTECCIÓN DE DATOS"}</span><h3>{legal==="waiver"?"Carta responsiva":"Aviso de privacidad"}</h3><div className="legal-document">{(legal==="waiver"?event.waiver:event.privacy)||"Nesport aún no ha publicado este documento. No continúes con el registro y comunícate con el organizador."}</div><button className="btn primary" onClick={()=>setLegal(null)}>Entendido</button></article></div>}</>
}
