"use client";
import{useMemo,useState}from"react";
import{CalendarPlus,Check,Clock3,ExternalLink,FileImage,Flag,LayoutDashboard,LogOut,Medal,Plus,Search,Trash2,Users}from"lucide-react";
import type{AdminEvent,AdminRegistration}from"./page";

type Tab="summary"|"runners"|"events"|"results";
const format=(ms:number|null)=>ms==null?"—":new Date(ms).toISOString().slice(11,23);
const statusLabel:Record<string,string>={pending:"Pendiente",approved:"Aprobado",rejected:"Rechazado",published:"Publicada",coming_soon:"Próxima",closed:"Cerrada",draft:"Borrador"};

export default function DashboardClient({rows:initial,events:initialEvents,connectionError}:{rows:AdminRegistration[];events:AdminEvent[];connectionError:string}){
 const[rows,setRows]=useState(initial),[events,setEvents]=useState(initialEvents),[tab,setTab]=useState<Tab>("summary"),[modal,setModal]=useState(false),[query,setQuery]=useState(""),[eventFilter,setEventFilter]=useState("all"),[notice,setNotice]=useState(connectionError),[busy,setBusy]=useState(false);
 const eventName=(id:string)=>events.find(e=>e.id===id)?.title||"Carrera no disponible";
 const filtered=useMemo(()=>rows.filter(x=>(eventFilter==="all"||x.event_id===eventFilter)&&(x.full_name+x.folio+x.email+eventName(x.event_id)).toLowerCase().includes(query.toLowerCase())),[rows,eventFilter,query,events]);
 const pending=rows.filter(x=>x.payment_status==="pending").length;
 async function payment(id:string,status:"approved"|"rejected"){const r=await fetch("/api/admin/registrations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});const j=await r.json();if(r.ok)setRows(rows.map(x=>x.id===id?{...x,payment_status:status}:x));else setNotice(j.error||"No se pudo actualizar el pago")}
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice("");try{const full=new FormData(e.currentTarget),kinds=["heroImage","shirtImage","bibImage","medalImage","kitImage"];const files=kinds.map(kind=>({kind,file:full.get(kind)})).filter(x=>x.file instanceof File&&(x.file as File).size>0)as{kind:string;file:File}[];for(const{file}of files)if(file.size>4*1024*1024)throw new Error(`${file.name} supera 4 MB. Reduce su tamaño antes de subirla.`);for(const kind of kinds)full.delete(kind);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);const r=await fetch("/api/admin/events",{method:"POST",body:full,signal:controller.signal});clearTimeout(timer);const j=await r.json().catch(()=>({error:`El servidor respondió ${r.status}. Revisa las variables de Supabase en Vercel.`}));if(!r.ok)throw new Error(j.error||"No fue posible crear la carrera");for(const{kind,file}of files){setNotice(`Carrera creada. Subiendo ${file.name}...`);const media=new FormData();media.set("eventId",j.id);media.set("kind",kind);media.set("file",file);const upload=await fetch("/api/admin/events/media",{method:"POST",body:media});const answer=await upload.json().catch(()=>({error:`No se pudo procesar ${file.name}`}));if(!upload.ok)throw new Error(answer.error||`No se pudo subir ${file.name}`)}setModal(false);location.reload()}catch(error){setNotice(error instanceof DOMException&&error.name==="AbortError"?"La solicitud tardó demasiado. Revisa SUPABASE_URL y SUPABASE_SECRET_KEY en Vercel.":error instanceof Error?error.message:"No se pudo guardar la carrera")}finally{setBusy(false)}}
 async function changeEvent(id:string,status:string){const r=await fetch("/api/admin/events",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(r.ok)setEvents(events.map(e=>e.id===id?{...e,status}:e));}
 async function removeEvent(id:string){if(!confirm("¿Eliminar esta carrera? Si tiene participantes, ciérrala en lugar de eliminarla."))return;const r=await fetch("/api/admin/events",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const j=await r.json();if(r.ok)setEvents(events.filter(e=>e.id!==id));else setNotice(j.error)}
 const results=[...filtered].filter(x=>x.race_time_ms!=null).sort((a,b)=>(a.race_time_ms||0)-(b.race_time_ms||0));
 return <main className="dashboard"><aside><a className="logo-brand" href="/"><img src="/nesport-logo.png" alt="Nesport"/></a><nav><button className={tab==="summary"?"active":""} onClick={()=>setTab("summary")}><LayoutDashboard/>Resumen</button><button className={tab==="runners"?"active":""} onClick={()=>setTab("runners")}><Users/>Corredores</button><button className={tab==="events"?"active":""} onClick={()=>setTab("events")}><CalendarPlus/>Carreras</button><button className={tab==="results"?"active":""} onClick={()=>setTab("results")}><Clock3/>Resultados</button></nav><a className="signout" href="/signout-with-chatgpt?return_to=/"><LogOut/>Cerrar sesión</a></aside><section className="dash-content"><header><div><small>PANEL DE CONTROL</small><h1>Nesport Admin</h1><p>Organización, registros, pagos y resultados por carrera.</p></div><button className="btn primary" onClick={()=>setModal(true)}><Plus/>Nueva carrera</button></header>{notice&&<div className="admin-alert"><b>Atención:</b> {notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className="stats"><article><span>CARRERAS</span><b>{events.length}</b><Flag/></article><article><span>PARTICIPANTES</span><b>{rows.length}</b><Users/></article><article><span>PAGOS PENDIENTES</span><b>{pending}</b><Clock3/></article><article><span>TIEMPOS RECIBIDOS</span><b>{rows.filter(x=>x.race_time_ms!=null).length}</b><Medal/></article></div>
 {tab==="summary"&&<div className="admin-grid"><section className="panel admin-card"><span>OPERACIÓN</span><h2>Estado de las carreras</h2>{events.length?events.slice(0,5).map(e=><div className="compact-event" key={e.id}><div>{e.hero_image?<img src={e.hero_image} alt=""/>:<Flag/>}<span><b>{e.title}</b><small>{new Date(e.event_date).toLocaleDateString("es-MX")}</small></span></div><em className={`status ${e.status}`}>{statusLabel[e.status]}</em></div>):<p className="empty-row">No hay carreras. Crea la primera desde el botón superior.</p>}</section><section className="panel admin-card"><span>PENDIENTES</span><h2>Pagos por revisar</h2>{rows.filter(x=>x.payment_status==="pending").slice(0,5).map(x=><div className="pending-item" key={x.id}><span><b>{x.full_name}</b><small>{eventName(x.event_id)} · {x.folio}</small></span><button onClick={()=>setTab("runners")}>Revisar</button></div>)}{!pending&&<p className="empty-row">No hay pagos pendientes.</p>}</section></div>}
 {(tab==="runners"||tab==="results")&&<div className="panel"><div className="panel-head"><div><span>{tab==="results"?"CLASIFICACIÓN":"PARTICIPANTES"}</span><h2>{tab==="results"?"Resultados por carrera":"Registros y comprobantes"}</h2></div><div className="admin-filters"><select value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option value="all">Todas las carreras</option>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><label><Search/><input placeholder="Nombre, folio o correo" value={query} onChange={e=>setQuery(e.target.value)}/></label></div></div>{tab==="runners"?<div className="table-wrap"><table><thead><tr><th>Corredor</th><th>Carrera</th><th>Folio</th><th>Categoría</th><th>Pago</th><th>Comprobante</th><th>Acciones</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.full_name}</b><small>{x.email} · {x.phone}</small></td><td>{eventName(x.event_id)}</td><td>{x.folio}</td><td>{x.category}<small>Talla {x.shirt_size}</small></td><td><span className={`status ${x.payment_status}`}>{statusLabel[x.payment_status]}</span></td><td><a className="table-link" target="_blank" href={`/api/admin/receipts?key=${encodeURIComponent(x.receipt_key)}`}><FileImage/>Ver <ExternalLink/></a></td><td><div className="row-actions"><button onClick={()=>payment(x.id,"approved")}><Check/>Aprobar</button><button className="danger" onClick={()=>payment(x.id,"rejected")}>Rechazar</button></div></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="empty-row">No hay participantes con estos filtros.</td></tr>}</tbody></table></div>:<div className="results-board">{results.map((x,i)=><article key={x.id}><strong>{i+1}</strong><div><b>{x.full_name}</b><span>{eventName(x.event_id)} · {x.category} · {x.folio}</span></div><time>{format(x.race_time_ms)}</time></article>)}{!results.length&&<p className="empty-row">Todavía no hay tiempos para esta carrera.</p>}</div>}</div>}
 {tab==="events"&&<div className="event-admin-grid">{events.map(e=><article className="event-admin-card" key={e.id}>{e.hero_image?<img src={e.hero_image} alt={e.title}/>:<div className="event-placeholder"><Flag/></div>}<div><span className={`status ${e.status}`}>{statusLabel[e.status]}</span><h2>{e.title}</h2><p>{e.location} · {new Date(e.event_date).toLocaleDateString("es-MX")}</p><div className="event-actions"><a href={`/carreras/${e.slug}`} target="_blank">Ver página</a><select value={e.status} onChange={x=>changeEvent(e.id,x.target.value)}><option value="draft">Borrador</option><option value="coming_soon">Próxima</option><option value="published">Publicada</option><option value="closed">Cerrada</option></select><button onClick={()=>removeEvent(e.id)}><Trash2/></button></div></div></article>)}{!events.length&&<div className="panel empty-row">No hay carreras creadas.</div>}</div>}
 </section>{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><form className="event-modal" onSubmit={create} onMouseDown={e=>e.stopPropagation()}><div><small>NUEVA CARRERA</small><h2>Crear experiencia</h2><p>Publica toda la información y las imágenes oficiales del evento.</p></div><label>Nombre<input required name="title"/></label><label>Descripción<textarea required name="description"/></label><div className="form-grid"><label>Fecha y hora<input required type="datetime-local" name="eventDate"/></label><label>Lugar<input required name="location"/></label><label>Precio<input required type="number" min="0" name="price"/></label><label>Estado<select name="status" defaultValue="published"><option value="published">Inscripciones abiertas</option><option value="coming_soon">Próximamente</option><option value="draft">Borrador</option></select></label><label className="wide">Categorías<input required name="categories" placeholder="5K Libre, 10K Libre"/></label><label className="wide">Incluye<input required name="includes" placeholder="Playera, medalla, dorsal, hidratación..."/></label><label className="wide">Premios<textarea name="prizes" placeholder="Premios por categoría y rama"/></label><label className="wide">Preguntas frecuentes<textarea name="faq" placeholder="Pregunta | Respuesta (una por línea)"/></label></div><fieldset><legend>Imágenes oficiales</legend><div className="image-upload-grid"><label>Portada<input name="heroImage" type="file" accept="image/*"/></label><label>Playera<input name="shirtImage" type="file" accept="image/*"/></label><label>Dorsal<input name="bibImage" type="file" accept="image/*"/></label><label>Medalla<input name="medalImage" type="file" accept="image/*"/></label><label>Kit<input name="kitImage" type="file" accept="image/*"/></label></div></fieldset><div className="form-grid"><label>Banco<input required name="bankName"/></label><label>Titular<input required name="bankHolder"/></label><label>Cuenta<input required name="bankAccount"/></label><label>CLABE<input required name="bankClabe"/></label></div><label>Carta responsiva<textarea required name="waiver"/></label><label>Aviso de privacidad<textarea required name="privacy"/></label><div className="form-actions"><button type="button" className="btn ghost" onClick={()=>setModal(false)}>Cancelar</button><button disabled={busy} className="btn primary">{busy?"Guardando...":"Crear carrera"}</button></div></form></div>}</main>
}
